apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: piepie
spec:
  schedule: "*/1 * * * *" 
  jobTemplate:            
    spec:
      template:
        metadata:
          labels:         
            parent: "cronjobpi"
        spec:
          containers:
          - name: pi
            image: perl
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(1999)"]
          restartPolicy: OnFailure
